# Generated by Django 3.2.9 on 2021-12-05 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupVK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField(unique=True, verbose_name='id Group')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Group Vk',
                'verbose_name_plural': 'Groups Vk',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('message', models.JSONField(blank=True, null=True, verbose_name='содержимое сообщения (JSON)')),
                ('send_message', models.BooleanField(default=False)),
                ('group_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duplicateMessage.groupvk', verbose_name='Group User')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'Groups User',
            },
        ),
    ]
